# Nama workflow yang akan ditampilkan di tab "Actions" GitHub
name: ML Model CI - Train and Register

# Trigger untuk menjalankan workflow
on:
  push:
    branches:
      - main  # Jalankan saat ada push ke branch main
  pull_request:
    branches:
      - main  # Jalankan saat ada pull request ke branch main

jobs:
  train-and-register-model:
    # Menggunakan runner Ubuntu versi terbaru
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup Conda env dari file dan langsung aktifkan
      # Action ini akan secara otomatis:
      # 1. Menginstal Mambaforge.
      # 2. Membuat environment dari file conda.yaml.
      # 3. Mengaktifkan environment tersebut untuk semua langkah selanjutnya.
      - name: Set up Conda environment from file
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Secara otomatis membuat dan mengaktifkan environment dari file ini
          environment-file: MLProject/conda.yaml
          
          # Menggunakan Mamba untuk instalasi yang lebih cepat
          use-mamba: true
          
          # Nama environment yang akan diaktifkan (harus sesuai dengan nama di conda.yaml)
          # Ganti 'churn-prediction-env' jika nama di file Anda berbeda
          activate-environment: mlflow_churn_env

      # Langkah 3: Menjalankan skrip training model
      # Environment Conda sudah aktif dari langkah sebelumnya.
      - name: Run ML Training and Registration Script
        # 'shell: bash -l {0}' memastikan shell diinisialisasi dengan benar untuk Conda
        shell: bash -l {0}
        env:
          # Variabel environment ini akan diambil dari GitHub Secrets
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          echo "Running training script in Conda environment..."
          # Tidak perlu 'conda activate' lagi di sini
          python MLProject/modelling.py
