name: Train ML Model via MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow_churn_env
        environment-file: mlproject/conda.yaml
        auto-activate-base: false
        use-mamba: true
        update-conda: false  # 💡 penting: pakai create, bukan update

    - name: Verify conda env
      run: conda info --envs

    - name: Run MLflow project
      run: |
        cd mlproject
        mlflow run . --env-manager=local
