name: ML Model CI - Train and Register

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-register-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment from file
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          use-mamba: true
          activate-environment: mlflow_churn_env

      - name: Run ML Training and Registration Script
        working-directory: ./MLProject
        shell: bash -l {0}
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in current directory..."
          ls -la
          echo "Running training script in Conda environment..."
          python modelling.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-ml-model
          path: MLProject/artifacts/  # Ganti sesuai path file hasil model
