name: Run MLflow Project with Model Registry

on:
  push:
    branches:
      - main

jobs:
  train-and-log:
    name: Train Model and Log with MLflow
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: http://your-tracking-server:5000  # Ganti dengan URI Tracking MLflow kamu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-file: MLProject/conda.yaml
          environment-name: mlflow_churn_env
          init-shell: bash
          cache-environment: true

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run . --no-conda
